# Generated by Django 5.2.1 on 2025-05-26 04:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Hình ảnh sản phẩm",
                "verbose_name_plural": "Hình ảnh sản phẩm",
            },
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Đánh giá sản phẩm",
                "verbose_name_plural": "Đánh giá sản phẩm",
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="sales_order_status_6d9527_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="sales_order_created_053ec8_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="sales_produ_name_db278d_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="sales_produ_categor_341ed2_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="note",
        ),
        migrations.RemoveField(
            model_name="order",
            name="voucher",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="product",
            name="harvest",
        ),
        migrations.RemoveField(
            model_name="product",
            name="original_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="view_count",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="is_main",
        ),
        migrations.AddField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(blank=True, null=True, verbose_name="Hạn sử dụng"),
        ),
        migrations.AddField(
            model_name="product",
            name="harvest_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày thu hoạch"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_organic",
            field=models.BooleanField(default=False, verbose_name="Hữu cơ"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("fresh", "Tươi sống"),
                    ("processed", "Đã chế biến"),
                    ("packaged", "Đóng gói sẵn"),
                ],
                default="fresh",
                max_length=20,
                verbose_name="Loại sản phẩm",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Văn bản thay thế"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Hình mặc định"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Thứ tự hiển thị"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật lần cuối"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Hiển thị công khai"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật lần cuối"),
        ),
        migrations.AddField(
            model_name="productreview",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="for_first_time_buyers",
            field=models.BooleanField(
                default=False, verbose_name="Cho khách mua lần đầu"
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="for_organic_products",
            field=models.BooleanField(
                default=False, verbose_name="Cho sản phẩm hữu cơ"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.voucher",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales.product"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xử lý"),
                    ("confirmed", "Đã xác nhận"),
                    ("processing", "Đang chuẩn bị hàng"),
                    ("shipped", "Đang giao hàng"),
                    ("delivered", "Đã giao hàng"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Số lượng",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="sales.productcategory",
                verbose_name="Danh mục",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(default="kg", max_length=20, verbose_name="Đơn vị"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="sales.productcategory",
                verbose_name="Danh mục cha",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="product_images/", verbose_name="Hình ảnh"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="sales.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Nhận xét"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="sales.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.IntegerField(
                default=5,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Đánh giá (sao)",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="max_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Giảm tối đa",
            ),
        ),
    ]
