# Generated by Django 5.2.1 on 2025-05-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
        ),
    ]
