# Generated by Django 5.2.1 on 2025-05-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Loại vật nuôi"),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tên khoa học"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "average_lifespan",
                    models.PositiveIntegerField(
                        verbose_name="Tuổi thọ trung bình (năm)"
                    ),
                ),
                (
                    "maturity_age",
                    models.PositiveIntegerField(
                        verbose_name="Tuổi trưởng thành (tháng)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="animal_types/", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loại vật nuôi",
                "verbose_name_plural": "Loại vật nuôi",
            },
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Giống")),
                (
                    "origin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nguồn gốc"
                    ),
                ),
                (
                    "characteristics",
                    models.TextField(blank=True, verbose_name="Đặc điểm"),
                ),
                (
                    "animal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breeds",
                        to="livestock.animaltype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Giống vật nuôi",
                "verbose_name_plural": "Giống vật nuôi",
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số hiệu"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Đực"), ("female", "Cái")],
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                ("acquisition_date", models.DateField(verbose_name="Ngày nhập về")),
                (
                    "acquisition_source",
                    models.CharField(max_length=100, verbose_name="Nguồn gốc"),
                ),
                (
                    "status",
                    models.CharField(
                        default="healthy", max_length=100, verbose_name="Tình trạng"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="farm.farm",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="livestock.animal",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="livestock.breed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vật nuôi",
                "verbose_name_plural": "Vật nuôi",
            },
        ),
    ]
