# Generated by Django 5.2.1 on 2025-05-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("farm", "0002_alter_farmmembership_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_users",
                to="farm.farm",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Quản trị viên"),
                    ("farm_manager", "Quản lý nông trại"),
                    ("farmer", "Nông dân"),
                    ("sales", "Nhân viên bán hàng"),
                    ("customer", "Khách hàng"),
                ],
                default="customer",
                max_length=20,
                verbose_name="Vai trò",
            ),
        ),
    ]
