# Generated by Django 5.2.1 on 2025-05-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_current_farm_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuration",
            options={
                "verbose_name": "Cấu hình hệ thống",
                "verbose_name_plural": "Các cấu hình hệ thống",
            },
        ),
    ]
