# Generated by Django 5.2.1 on 2025-07-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_configuration_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Quản trị viên"), ("customer", "Khách hàng")],
                default="customer",
                max_length=20,
                verbose_name="Vai trò",
            ),
        ),
    ]
