# Generated by Django 5.2.1 on 2025-07-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="Ảnh đại diện"
            ),
        ),
    ]
