# Generated by Django 5.2.1 on 2025-07-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_profiles/",
                verbose_name="Ảnh đại diện",
            ),
        ),
    ]
