# Generated by Django 5.2.1 on 2025-05-23 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Giống cây"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Dự kiến trồng"),
                            ("seedling", "Cây giống"),
                            ("growing", "Đang phát triển"),
                            ("harvested", "Đã thu hoạch"),
                            ("failed", "Thất bại"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "planting_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày trồng"),
                ),
                (
                    "harvest_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày thu hoạch"
                    ),
                ),
                (
                    "area",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Diện tích (ha)",
                    ),
                ),
                (
                    "expected_yield",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Năng suất dự kiến (tấn/ha)"
                    ),
                ),
                (
                    "actual_yield",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Năng suất thực tế (tấn/ha)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="farm.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cây trồng",
                "verbose_name_plural": "Cây trồng",
                "ordering": ["-planting_date"],
            },
        ),
        migrations.CreateModel(
            name="CropStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Giai đoạn")),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày kết thúc"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Hoàn thành"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="crop.crop",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Giai đoạn cây trồng",
                "verbose_name_plural": "Giai đoạn cây trồng",
            },
        ),
        migrations.CreateModel(
            name="CropType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên loại cây")),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tên khoa học"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "growth_duration",
                    models.PositiveIntegerField(
                        verbose_name="Thời gian sinh trưởng (ngày)"
                    ),
                ),
                (
                    "optimal_temperature_min",
                    models.FloatField(verbose_name="Nhiệt độ tối thiểu (°C)"),
                ),
                (
                    "optimal_temperature_max",
                    models.FloatField(verbose_name="Nhiệt độ tối đa (°C)"),
                ),
                (
                    "optimal_ph_min",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                        verbose_name="Độ pH tối thiểu",
                    ),
                ),
                (
                    "optimal_ph_max",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                        verbose_name="Độ pH tối đa",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="crop_types/", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loại cây trồng",
                "verbose_name_plural": "Loại cây trồng",
            },
        ),
        migrations.AddField(
            model_name="crop",
            name="crop_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crops",
                to="crop.croptype",
            ),
        ),
    ]
