# Generated by Django 5.2.1 on 2025-05-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crop", "0001_initial"),
        ("farm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Harvest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("harvest_date", models.DateField(verbose_name="Ngày thu hoạch")),
                ("quantity", models.FloatField(verbose_name="Sản lượng")),
                (
                    "unit",
                    models.CharField(
                        default="kg", max_length=20, verbose_name="Đơn vị"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                        ],
                        max_length=20,
                        verbose_name="Chất lượng",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "storage_location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nơi lưu trữ"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvests",
                        to="crop.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvests",
                        to="farm.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thu hoạch",
                "verbose_name_plural": "Thu hoạch",
            },
        ),
    ]
