# Generated by Django 5.2.1 on 2025-05-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crop", "0001_initial"),
        ("farm", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fertilization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày bón")),
                ("amount", models.FloatField(verbose_name="Lượng bón (kg)")),
                (
                    "method",
                    models.CharField(max_length=100, verbose_name="Phương pháp"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fertilizations",
                        to="farm.farm",
                    ),
                ),
                (
                    "fertilizer",
                    models.ForeignKey(
                        limit_choices_to={"item_type": "fertilizer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "related_crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crop.crop",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bón phân",
                "verbose_name_plural": "Bón phân",
            },
        ),
        migrations.CreateModel(
            name="Irrigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("date", models.DateField(verbose_name="Ngày tưới")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("drip", "Tưới nhỏ giọt"),
                            ("sprinkler", "Tưới phun"),
                            ("flood", "Tưới ngập"),
                        ],
                        max_length=20,
                        verbose_name="Phương pháp",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(verbose_name="Thời gian (phút)"),
                ),
                ("water_amount", models.FloatField(verbose_name="Lượng nước (m3)")),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigations",
                        to="farm.farm",
                    ),
                ),
                (
                    "related_crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crop.crop",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tưới tiêu",
                "verbose_name_plural": "Tưới tiêu",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                ("due_date", models.DateField(verbose_name="Hạn hoàn thành")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Thấp"),
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Ưu tiên",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Hoàn thành"),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày hoàn thành"
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="farm.farm",
                    ),
                ),
                (
                    "related_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Công việc",
                "verbose_name_plural": "Công việc",
                "ordering": ["-due_date"],
            },
        ),
    ]
