# Generated by Django 5.2.1 on 2025-05-24 07:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_alter_farmmembership_options_and_more"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "report_date",
                    models.DateField(auto_now_add=True, verbose_name="Ngày báo cáo"),
                ),
                ("content", models.TextField(verbose_name="Nội dung báo cáo")),
                (
                    "progress",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Tiến độ (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Báo cáo công việc",
                "verbose_name_plural": "Báo cáo công việc",
                "ordering": ["-report_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="fertilization",
            options={
                "ordering": ["-date"],
                "verbose_name": "Bón phân",
                "verbose_name_plural": "Bón phân",
            },
        ),
        migrations.AlterModelOptions(
            name="irrigation",
            options={
                "ordering": ["-date"],
                "verbose_name": "Tưới tiêu",
                "verbose_name_plural": "Tưới tiêu",
            },
        ),
        migrations.RenameField(
            model_name="task",
            old_name="completion_date",
            new_name="completed_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="related_object_id",
        ),
        migrations.RemoveField(
            model_name="task",
            name="related_object_type",
        ),
        migrations.AddField(
            model_name="fertilization",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Đã lên kế hoạch"),
                    ("in_progress", "Đang thực hiện"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddField(
            model_name="fertilization",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fertilization_task",
                to="operations.task",
            ),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Đã lên kế hoạch"),
                    ("in_progress", "Đang thực hiện"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddField(
            model_name="irrigation",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="irrigation_task",
                to="operations.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="area",
            field=models.CharField(blank=True, max_length=100, verbose_name="Khu vực"),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Ngày bắt đầu"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ thực hiện"),
                    ("assigned", "Đã giao"),
                    ("in_progress", "Đang thực hiện"),
                    ("completed", "Hoàn thành"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="irrigation",
            name="method",
            field=models.CharField(
                choices=[
                    ("drip", "Tưới nhỏ giọt"),
                    ("sprinkler", "Tưới phun"),
                    ("flood", "Tưới ngập"),
                    ("manual", "Tưới thủ công"),
                ],
                max_length=20,
                verbose_name="Phương pháp",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Thấp"),
                    ("medium", "Trung bình"),
                    ("high", "Cao"),
                    ("urgent", "Khẩn cấp"),
                ],
                default="medium",
                max_length=20,
                verbose_name="Ưu tiên",
            ),
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="task_attachments/", verbose_name="File đính kèm"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="Mô tả"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="operations.task",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File đính kèm công việc",
                "verbose_name_plural": "File đính kèm công việc",
            },
        ),
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên danh mục")),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "color",
                    models.CharField(
                        default="#4CAF50",
                        max_length=20,
                        verbose_name="Màu sắc hiển thị",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_categories",
                        to="farm.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục công việc",
                "verbose_name_plural": "Danh mục công việc",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="operations.taskcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["farm", "status"], name="operations__farm_id_2580a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "due_date"],
                name="operations__assigne_bdfe98_idx",
            ),
        ),
        migrations.AddField(
            model_name="taskreport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskreport",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="operations.task",
            ),
        ),
        migrations.AddField(
            model_name="taskreport",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="task_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="operations.taskreport",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskcategory",
            unique_together={("name", "farm")},
        ),
    ]
