# Generated by Django 5.2.1 on 2025-05-23 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên nông trại"),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("location", models.CharField(max_length=255, verbose_name="Địa điểm")),
                (
                    "area",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Diện tích (ha)",
                    ),
                ),
                (
                    "farm_type",
                    models.CharField(
                        choices=[
                            ("plant", "Trồng trọt"),
                            ("livestock", "Chăn nuôi"),
                            ("mixed", "Kết hợp"),
                        ],
                        max_length=20,
                        verbose_name="Loại hình nông trại",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Mô tả thêm"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "established_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày thành lập"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="farm_logos/",
                        verbose_name="Logo nông trại",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nông trại",
                "verbose_name_plural": "Nông trại",
            },
        ),
        migrations.CreateModel(
            name="FarmDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("license", "Giấy phép"),
                            ("certificate", "Chứng nhận"),
                            ("contract", "Hợp đồng"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="farm_documents/")),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="farm.farm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài liệu nông trại",
                "verbose_name_plural": "Tài liệu nông trại",
            },
        ),
        migrations.CreateModel(
            name="FarmMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Chủ sở hữu"),
                            ("manager", "Quản lý"),
                            ("worker", "Nhân viên"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farm.farm"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thành viên nông trại",
                "verbose_name_plural": "Thành viên nông trại",
            },
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["farm_type"], name="farm_farm_farm_ty_196384_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["is_active"], name="farm_farm_is_acti_3e8824_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farmmembership",
            unique_together={("farm", "user")},
        ),
    ]
