# Generated by Django 5.2.1 on 2025-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farmmembership",
            options={
                "ordering": ["-joined_date"],
                "verbose_name": "Thành viên nông trại",
                "verbose_name_plural": "Thành viên nông trại",
            },
        ),
        migrations.AddField(
            model_name="farmmembership",
            name="can_approve",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farmmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Quản lý"),
                    ("assistant_manager", "Phó quản lý"),
                    ("field_supervisor", "Giám sát đồng ruộng"),
                    ("farmer", "Nông dân"),
                    ("sales", "Nhân viên bán hàng"),
                ],
                max_length=20,
            ),
        ),
    ]
