# Generated by Django 5.2.1 on 2025-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên dashboard"),
                ),
                ("config", models.JSONField(verbose_name="Cấu hình")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Mặc định"),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("production", "Sản xuất"),
                            ("financial", "Tài chính"),
                            ("inventory", "Tồn kho"),
                            ("sales", "Bán hàng"),
                        ],
                        max_length=20,
                        verbose_name="Loại báo cáo",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("start_date", models.DateField(verbose_name="Từ ngày")),
                ("end_date", models.DateField(verbose_name="Đến ngày")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "file",
                    models.FileField(upload_to="reports/", verbose_name="File báo cáo"),
                ),
            ],
            options={
                "verbose_name": "Báo cáo",
                "verbose_name_plural": "Báo cáo",
            },
        ),
    ]
