# Generated by Django 5.2.1 on 2025-05-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboard",
            options={
                "verbose_name": "Bảng điều khiển",
                "verbose_name_plural": "Bảng điều khiển",
            },
        ),
    ]
