# Generated by Django 5.2.1 on 2025-05-24 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("farm", "0002_alter_farmmembership_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("task_completion", "Hoàn thành công việc"),
                            ("inventory_use", "Sử dụng vật tư"),
                            ("harvest", "Thu hoạch"),
                            ("product_publish", "Xuất bản sản phẩm"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                        verbose_name="Loại yêu cầu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                            ("changes_requested", "Yêu cầu thay đổi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày yêu cầu"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ngày phê duyệt"
                    ),
                ),
                ("related_object_id", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú yêu cầu")),
                (
                    "response_notes",
                    models.TextField(blank=True, verbose_name="Ghi chú phản hồi"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="farm.farm",
                    ),
                ),
                (
                    "related_object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu phê duyệt",
                "verbose_name_plural": "Yêu cầu phê duyệt",
                "ordering": ["-request_date"],
                "indexes": [
                    models.Index(
                        fields=["farm", "status"], name="approval_ap_farm_id_4fc960_idx"
                    ),
                    models.Index(
                        fields=["requester", "approver"],
                        name="approval_ap_request_51b5ce_idx",
                    ),
                ],
            },
        ),
    ]
