# Generated by Django 5.2.1 on 2025-05-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approvalrequest",
            name="request_type",
        ),
    ]
